run_new_simulation: True

# --- Run a new simulation with the following parameters ---
T_simulation: 60 # seconds
T_step: 0.3333333 # seconds
N_humans: 3
N_robots: 3

# --- Load a previous simulation (ignored if run_new_simulation == True) ---
# ignores the above parameters and uses the parameters from the log file
log_file: "log_2024-10-09_21-41-50.pkl"

# --- Plotting parameters ---
plot: True
record_video: False # sets plot to True
playback_speed: 0.5

# --- Tracker parameters ---
N_particles: 1000
N_humans_tracker: -1 # -1 same as in the simulation