# Simulation
# ----------------------------------------------------------------------
# --- Run a new simulation or load a previous one ---
# if True, loads a previous simulation from the folder
# if False, runs and saves new simulation under the folder
run_new_simulation: True
folder: "30min_4humans_4robots" # if empty, uses the current date and time

# --- Simulation parameters (only relevant when running a new simulation) ---
# if a previous simulation is used the parameters come from the previous simulation
T_simulation: 1800 # seconds
T_step: 0.5 # seconds
N_humans: 4
N_robots: 4


# Tracker
# ----------------------------------------------------------------------
# Set to false if you only want to run the simulation
run_tracker: True

# --- Tracker parameters ---
N_particles: 10000
N_tracks_init: 4

# --- Plotting parameters ---
plot: False
record_video: False # sets plot to True
playback_speed: 1 # 1 is normal speed
# maximum probability to consider an edge cleared
# only relevant for the plot and the final printed results
# The exact probabilities are logged,
# so you can always evaluate with a different threshold later
clear_threshold: 0.001 

