run_new_simulation: True

# --- Run a new simulation with the following parameters ---
T_simulation: 600 # seconds
T_step: 0.5 # seconds
N_humans: 3
N_robots: 4

# --- Load a previous simulation (ignored if run_new_simulation == True) ---
# ignores the above parameters and uses the parameters from the log file
log_file: "log_2024-10-23_19-23-37.pkl"

# --- Plotting parameters ---
plot: False
record_video: False # sets plot to True
playback_speed: 1 # 1 is normal speed
clear_threshold: 0.001 # maximum probability to consider an edge cleared

# --- Tracker parameters ---
N_particles: 1000
N_humans_tracker: 6 # -1 same as in the simulation